name: MatBlazor-Publish-Develop-CI

on [push]      

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: Run Nuke
        run: |
          ./build.sh Standard
        env:
          NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}          